apiVersion: apps/v1
kind: Deployment
metadata:
  name: cutest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cutest
  template:
    metadata:
      labels:
        app: cutest
    spec:
      containers:
        - name: cutest
          image: cutest
          ports:
            - containerPort: 8000